sudo: required

language: java
install: true

jdk:
- oraclejdk7

services:
- docker

script:
- mvn clean install -B -e -V -Plocal-depl-j2se-hsqldb -DpushImage --settings deploy-settings.xml

cache:
  directories:
  - "$HOME/.m2/repository"

notifications:
  email: marcus.maccio@gmail.com

marcomaccio/bankanalyzer-he:
  secure: "YZ5znsBuGsFKmkzhfkgTuV4tI2Qp4PJP7QPsxKlfb7KSHItp7r0rhyQmPD/K3p2jrHae0RglA6w/eZLFTTOU5DUkuEbeitHpRse7h6Vqy0WOX+Dmg3XKZarqcOmLzeP0V8Ca6K0iTjrXfFs3hsgfkWWLsk3rqpE3SbqzXsCN07b9Ow/z0emvEkIy1b2cyOiLF6LbXKpu4LtaXQhh6fBuWjrAcIKcIBCtbPNw8GCJcq1wU9Ys62pMY54ltc/oViyKtsFIpeP+aLFwHbnwshktoHcSeD7U4aaVnnAQBfzINs5MKO540vyK0PND7Q8RSlZu2Gv77ykBtzWenYkFvcNuSxmY+UFQ67bwNMTrOV1f6IlLLp7jMW27V3qmjg51iig0g+qUB71xInuHpW6OfIYBiYVUV8vOOhinLlZNX/N3rc7Ly1nht79BGGOaCCcXthjoCsjmsoP4EHDNb5D1VTofMsUDYL3UMhL/lcnaW4nMdeEx+4n7TQjwmnMMlH0exoAupiDGnV6wrpAhLALrGDSZcvzoSWW0kRdvPTk21A10c58Fi6Zk2xXRZTPkKbSnDXGP24IpDzNPE89Gzy2mAlmgH9ko74G6m2XnjLcWBS5Agp22L+nnBxPBdDlswWUE5b5lxnBJM7+kcET45hguViPLz6fKJ5P1Ze36sJVBEYdzD1Q="
  secure: "ex3sW5rpqAgbMJLbPLRJQYM5cLosSEuGdo+BGpy6w+NCMegFshMKHveW6W5Rm/RF+hRE2i7wfSNeKNaShlGTUnKSVJU4NFFFvOQ1fVbomeLmeGxwXGgOQJu2ZcBwSbe674S6WV74ZRvxCusGcy7ExByvAUUAmSYo1HgmqEkj29ICblcmwL6YvxU2fJ1u8gGZh0lUZdnVCNoqB4g81Udk5SuGUw2XJ3d4toKSCasQJBvgczmT49RztHr9NfCOPq809WCT5mVbGwt1hc57cinEctFfT0tq1NV7PUohpuO5DEKHmGCw4jYLPuw5S3eCSeMQVz3gjKokaIfaq1Za0OtzozegMS/Z6jPtPKZf6RD2mFzGzMGePzbxaCY9cg1rNUVz/TLjvwRUmvxggufNtQgjMsZvoZ2C4zjnHbYgNv9w6r18sdeGTgEEyUR9UQ785SuV91d/O+WihNV643GyMVWZKYEuIwb5Mj4juoDQFCa3MsVTzijqlo5VIkLnDNK4jwsQKHkxmeO3F5nOEbjO6u+xHlrebDmZhUkpRlt1MRjW9Vlq9DIo5b+L5XJpn7YdB6W2QLkZ4NL8WvfQRs3YrxLXGC/3GJ/bVwP2KxuGwFjFXSXqGsXdhAeAj2ji91fnhJj8S5BPVIYgkQjFBGYbZoTHcfQhRIXyMpAi0P5eJ/074AE="
  secure: "CC8hfLvu10o2yhjdqQhAi9JyYW4GXD0218SySLPdfUK++ZCMM1SQagB3SqqjxDMX6KXD91AdA2/ySBmC0k0DCGRWfaoRyJ2o9PcMBQOZ2oB3Kuzm62omVTIWOtVBCCdeTfaKmVj2UyiOLcFOEs4CtY5vyTjBr5qODxT5TeyTXbSwBs4Ac2A2ArfH4sZmCcARC/MOdv68cLqHCDooy/5uU/UPTIcyfOp0fN+72CnnjKmN+3OBwAw7nLf86F+CEl1XBPFPcFDqZyhQ5NgrohORyn2TezaiqWuJB+uh0GWkvT05jc9SpuE8n3ZxS8Ywb1nmwbZUGlmreE26j9NSCN8kwrRC1ijbmUVT0sU9pRGDmLoHuQCNdwB+1H1lJCtkIluZ55DhAAUE1Z10QUnx1kXWRo3+Z8qH+CCZZZEAIJfZPrVVE8caeNQvIbg/Cn1uczNwCSMeBwDLzmnhQvpm3Ku7972tZkqm/3OjXg9XPlQh9LU0HKnzD4rTdV5IRtKBpsVjt0vKFr8sKWOLpyoKWNrzW5fnot3s+SWUelbNWMjtjWYXRQ3nEJb+a9Td3LSZ1plXE322sB5Km24SRJqP495hvQELH3guAMWHtAK7tOAO0qfmYvC+WlMHkXra8ZL58uH+3ZgP6WMi4wucR92/ioRLDQud2MrdLw9XmiorJkd20+U="
