language: java
sudo: false
install: true
jdk:
- oraclejdk7
script:
- mvn clean install -B -e -V -Plocal-depl-j2se-hsqldb

cache:
  directories:
  - "$HOME/.m2/repository"
notifications:
  email: marcus.maccio@gmail.com