sudo: required

language: java
install: true

jdk:
- oraclejdk7

services:
- docker

script:
- mvn clean install -U -V -Plocal-depl-j2se-hsqldb --settings settings-travis.xml -Dsettings.security=settings-security.xml

after_success:
- docker build -t marcomaccio/bankanalyzer-he src/main/resources/docker/

cache:
  directories:
  - "$HOME/.m2/repository"

notifications:
  email: marcus.maccio@gmail.com

marcomaccio/bankanalyzer-he:
  secure: "YZ5znsBuGsFKmkzhfkgTuV4tI2Qp4PJP7QPsxKlfb7KSHItp7r0rhyQmPD/K3p2jrHae0RglA6w/eZLFTTOU5DUkuEbeitHpRse7h6Vqy0WOX+Dmg3XKZarqcOmLzeP0V8Ca6K0iTjrXfFs3hsgfkWWLsk3rqpE3SbqzXsCN07b9Ow/z0emvEkIy1b2cyOiLF6LbXKpu4LtaXQhh6fBuWjrAcIKcIBCtbPNw8GCJcq1wU9Ys62pMY54ltc/oViyKtsFIpeP+aLFwHbnwshktoHcSeD7U4aaVnnAQBfzINs5MKO540vyK0PND7Q8RSlZu2Gv77ykBtzWenYkFvcNuSxmY+UFQ67bwNMTrOV1f6IlLLp7jMW27V3qmjg51iig0g+qUB71xInuHpW6OfIYBiYVUV8vOOhinLlZNX/N3rc7Ly1nht79BGGOaCCcXthjoCsjmsoP4EHDNb5D1VTofMsUDYL3UMhL/lcnaW4nMdeEx+4n7TQjwmnMMlH0exoAupiDGnV6wrpAhLALrGDSZcvzoSWW0kRdvPTk21A10c58Fi6Zk2xXRZTPkKbSnDXGP24IpDzNPE89Gzy2mAlmgH9ko74G6m2XnjLcWBS5Agp22L+nnBxPBdDlswWUE5b5lxnBJM7+kcET45hguViPLz6fKJ5P1Ze36sJVBEYdzD1Q="
  secure: "HqNF5vjOJdHArOLyg91wi70ntGv4eS5eqERVU0yrqsg1qVaEL6AxGldXJIsvc9IkIeu+o1xpUwX6gbn4MA5ZoM2dw8DEvObCzjjX3u8q4WjSRG5lcLCMW8s3T0csq1FimJykx6wpuPudigtWrLfG70J2CVFYGa4x4Ht3AH5vyWR6sZUqvnF7YLccP0MBrWVYuHWS/fTnCmzKYCUyjijklLTpnDor14X7ZO9bqMmt+q/wSa6V4ie3q9s97hkF9Up358IB5cBsIkH5j21Pj1t4qtGWvVdDprn3xfU6scy35N6jj2mbLKUvJAN+U1JqVarevlOtkcRM2nKz82wIxiGKZD/pPHbFzrvtjqy7iWYr+I2QgX5eeQP3kSCoztDQlmYbUr4SSob4HLiWgsHgIxTD7JyY6cMtFbBa1kf4uh3XVE5CWDGYHgUmvGIneZeir+3F8+rDAdWdLKfhdtGUs3IbfM/D99rOJivCnpwG4ViaISnwdmcoNNHHyPbrPvFQsFN/5YxGNbIxmGaSQe6zDMfg8vJlfQcoRnTUH2l7DbyqfE/bZCt3SFwV6r9XKyqiwmVDcSmSSnrXOu2D8J61ym1Qkdkp8bxclUBswsHlAK40xW/Ekw8S2xWk6JCPDx0Pfos76NDorNe+Lj7+CGvqhDEUg2ayFz2n2ypuoEO46ivCTIo="
  secure: "CC8hfLvu10o2yhjdqQhAi9JyYW4GXD0218SySLPdfUK++ZCMM1SQagB3SqqjxDMX6KXD91AdA2/ySBmC0k0DCGRWfaoRyJ2o9PcMBQOZ2oB3Kuzm62omVTIWOtVBCCdeTfaKmVj2UyiOLcFOEs4CtY5vyTjBr5qODxT5TeyTXbSwBs4Ac2A2ArfH4sZmCcARC/MOdv68cLqHCDooy/5uU/UPTIcyfOp0fN+72CnnjKmN+3OBwAw7nLf86F+CEl1XBPFPcFDqZyhQ5NgrohORyn2TezaiqWuJB+uh0GWkvT05jc9SpuE8n3ZxS8Ywb1nmwbZUGlmreE26j9NSCN8kwrRC1ijbmUVT0sU9pRGDmLoHuQCNdwB+1H1lJCtkIluZ55DhAAUE1Z10QUnx1kXWRo3+Z8qH+CCZZZEAIJfZPrVVE8caeNQvIbg/Cn1uczNwCSMeBwDLzmnhQvpm3Ku7972tZkqm/3OjXg9XPlQh9LU0HKnzD4rTdV5IRtKBpsVjt0vKFr8sKWOLpyoKWNrzW5fnot3s+SWUelbNWMjtjWYXRQ3nEJb+a9Td3LSZ1plXE322sB5Km24SRJqP495hvQELH3guAMWHtAK7tOAO0qfmYvC+WlMHkXra8ZL58uH+3ZgP6WMi4wucR92/ioRLDQud2MrdLw9XmiorJkd20+U="
  secure: "RtS8GaIuEWm+piGMg+3gWDwuhb264H9fjeF8mWpviP17TZO+K6dBBJJKjNMRCqe9yWcUcO4fssfouHfRdPdV8qAx+Z9j571Bz9ZiYa19MTtb3nSFZ1eA8DtMjkgd1m8axi0mFv7RF8mjL60TLqAl0QgDZvIE1ULB4xZ/GyjaJY0x7DdU/gLeLlRiCFJ91cheFUfrdecXnit5d8SzlVUox9KTJt7ByCF/9c2NUA3xmm/ZZpHVVLqduP63K9CzZSW8+O80va9obo+VvSIhGQGJY/wHQgeCoRThWOE0tNrt41d4l96JfDQH3I2nfNwI5/FuLBoqCTzxWKRvhEPacBCwcZMj57EpyiLBFg5AGhyS8hK+CSOGR4Sf681hZTK3DbHqRay6pnrd1QgFyDp2mz3vT4m868FEKATYW6/3BBIVLhfJb7Dx570+TgFtUNhBhAEfFPvmYJxKwMg1m7sqRhgycm/POj2Dl1VUsmeuT6mdMa7iMyOcTPcOw2ibcxulv8OBxfSkY7ArR4besojcrF0Z9U4mJHXCzZsioYBTBl05jhcjH/dPuaCyROXZZs5Fhbs4a9I0YRlBL77vDedQzywo5ay5swB0UPRQqKjp4eWKrPMWRxW/kvJMS2dsJ80zCFUaDEzULuNdm/qEQnCFKd3JGI1pEYqPUJAqfll63oWc7yo="
